#!/usr/bin/env bash

set -e

if [[ -z "${1}" ]]; then
  DOWNLOAD_URL="$(./latest-download-url)"
  VERSION=$(./url-to-version "${DOWNLOAD_URL}")
  docker build \
    --tag hugojosefson/webstorm:${VERSION} \
    --tag hugojosefson/webstorm:latest \
    .
else
  DOWNLOAD_URL="${1}"
  VERSION=$(./url-to-version "${DOWNLOAD_URL}")
  docker build \
    --tag hugojosefson/webstorm:${VERSION} \
    .
fi
