#!/usr/bin/env bash

set -e

if [[ "$(basename ${1} .sh) ${2}" == "webstorm --version" ]]; then
  cat /opt/webstorm/product-info.json | jq -r .version
  exit 0
fi

if ! [[ $EUID == 0 ]]; then
  echo "This docker image must be started as root, so don't use 'docker run --user=...'." >&2
  echo "Instead, pass environment variables USER_NAME, USER_ID, GROUP_NAME, GROUP_ID (and optionally HOME) for the user you want to become." >&2
  exit 1
fi

if [[ "|${USER_NAME}|${USER_ID}|${GROUP_NAME}|${GROUP_ID}" == *"||"* ]]; then
  echo "You must pass env variables USER_NAME, USER_ID, GROUP_NAME, GROUP_ID to the Docker container." >&2
  echo "Passing env variable HOME is optional." >&2
  exit 1
fi
HOME=${HOME:-"/home/${USER_NAME}"}
WEBIDE_VM_OPTIONS="-Duser.home=${HOME} -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"

groupadd \
  --gid "${GROUP_ID}" \
  "${GROUP_NAME}"

if [[ -d "$HOME" ]]; then
  CREATE_HOME=""
else
  CREATE_HOME="--create-home"
fi

useradd \
  --uid "${USER_ID}" \
  --gid "${GROUP_ID}" \
  --groups nvm,video \
  ${CREATE_HOME} \
  --home-dir "${HOME}" \
  "${USER_NAME}"

exec gosu "${USER_ID}:${GROUP_ID}" "$@"
