#!/usr/bin/env bash

set -e

WEBSTORM_URL="${1:-$($(dirname ${0})/latest-webstorm-url)}"
INSTALL_DIR="/opt/webstorm"

mkdir -p "${INSTALL_DIR}"
curl --silent --location "${WEBSTORM_URL}" \
  | tar xz \
    --strip-components 1 \
    --directory "${INSTALL_DIR}"

ln -s ${INSTALL_DIR}/bin/webstorm.sh /usr/local/bin/webstorm
